### ISSUE TITLE
Request for Option to disable link to twitch.tv on stream click

### ISSUE THREAD

**Issue by frango9000** [bhamrick/multitwitch#14]

**Comment by frango9000** [comment]
so double click on stream would go fullscreen

**Comment by CaitSith2** [comment]
Ditto,  it is too easy to accidentally click the stream.  twitch's latest iteration of the player disables this, but unfortunately, the latest iteration is NOT used here, which means click one of the views accidentally and it gets redirected to the specific twitch channel.  Also, a popout option would be nice.

**Comment by frango9000** [comment]
This issue was unintentionally solved by HTML5 migration:

https://github.com/bhamrick/multitwitch/commit/b46f5571f303a612c318b04e8c740fa889ab804d

It can be tagged as closed.
