### ISSUE TITLE
Please setup HTTPS for multitwitch.tv

### ISSUE THREAD

**Issue by JoshuaACasey** [bhamrick/multitwitch#24]
See title

**Comment by tony678933** [comment]
It seems as though there already is https functionality
![image](https://user-images.githubusercontent.com/49970595/156969762-cf2eef01-9f8c-42f6-a041-1ff07dd702ab.png)

**Comment by bhamrick** [comment]
As mentioned, https should be set up. Please reopen with more information if it doesn't seem to work for you.
