### ISSUE TITLE
Suggestion: Add Option for Dark Themed Chat

### ISSUE THREAD

**Issue by brad-charboneau** [bhamrick/multitwitch#30]
Like Twitch itself it would be nice to have multitwitch.tv's chat also be dark themed. the feature should be optional so that each user can select their own preferred chatbox color. If I had time I would make the changes myself and submit a pull request.

**Comment by TheTedAdams** [comment]
Looking into how to do this, I think currently an older format of the chat embed URI is being used:

```js
<iframe [...] src="http://twitch.tv/chat/embed?channel=' + name + '&popout_chat=true"></iframe>
```

So current URI format is
```js
'http://twitch.tv/chat/embed?channel=' + name + '&popout_chat=true'
```

Looks like this now redirects to URI of the format:
```js
'https://www.twitch.tv/embed/' + name + '/chat'
```

And in that URI format we can just add the param `?darkpopout`
```js
'https://www.twitch.tv/embed/' + name '/chat?darkpopout'
```

This could easily be managed via a new button with the other two links at the bottom.

I was going to throw together a PR for this, but after getting python set up on my machine one of the dependencies doesn't seem to work in python 3... so maybe another day.

**Comment by NDelt** [comment]
I want this feature too.

**Comment by deanveloper** [comment]
I'll see if I can make a pull request

**Comment by deanveloper** [comment]
Made a pull request: https://github.com/bhamrick/multitwitch/pull/40

**Comment by Nicholi** [comment]
Added my own pull request, which just pulls from querystring intead of addng new UI elements. Unsure if that will make it more likely to get merged. Really hating the blaring white chat.

https://github.com/bhamrick/multitwitch/pull/45
