### ISSUE TITLE
I think you've been hacked.

### ISSUE THREAD

**Issue by Tritiumnzlol** [bhamrick/multitwitch#31]
Every stream just redirects to ShadBaseMurderTV.

e.g.
[http://multitwitch.tv/ziggydlive/zizaran/RaizQT/tarkecat](http://multitwitch.tv/ziggydlive/zizaran/RaizQT/tarkecat)

**Comment by bhamrick** [comment]
Is this still happening for you? Everything seems to be working for me as expected. But I got another person sending me essentially the same issue 10 minutes ago, but with a different target stream. Can you also check if it happens on the main twitch site as well? It would also be helpful if you could check other multi-stream viewers like kadgar.net/live and see if the issue happens there.

**Comment by stevetheclimber** [comment]
I have been having this same issue for several days where ShadBaseMurderTV replaces any streams I use in multitwitch. I am using Chrome, and have tried restarting Chrome and using an incognito tab. I tried using multitwitch in Microsoft Edge and it appears to work fine. Multistre.am is working fine, so I've been using that until multitwitch starts working again.
