### ISSUE TITLE
Twitch embedded player updates break functionality completely

### ISSUE THREAD

**Issue by DcBexter** [bhamrick/multitwitch#44]
Changes: https://discuss.dev.twitch.tv/t/twitch-embedded-player-updates-in-2020/23956

These came in effect on June 10, 2020.

![image](https://user-images.githubusercontent.com/2346602/84326636-b1c59880-ab7d-11ea-8562-6897ed000102.png)

The fix would be to include the parent parameter in the iframe
See required parameter for interactive live streams: https://dev.twitch.tv/docs/embed/video-and-clips/

**Comment by bhamrick** [comment]
Thanks! This also involved setting up SSL (which I should've done previously anyway...).

Reopen this issue and let me know if anything isn't working correctly. I did a quick test with both loading the page and changing streams on the page but may have missed something. You might need to make sure you're getting the new js as well if a newly added stream fails to load (e.g. ctrl-shift-R)
